config/routes.rb
Crowdvocate::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { :registrations => "user/registrations", :sessions => "user/sessions" }
  devise_scope :user do
    #get 'account(/:id)', :action => 'edit', :controller => 'user/registrations', :as => 'account'
  end
  ActiveAdmin.routes(self)
  match "/admin" => "admin/dashboard#index", via: :get

  get "pages/home"
  resources :projects do
    resources :events do
      resources :comments, only: [:create]
    end
    resources :pledges, only: [:create, :update]
    resources :videos do
      resources :votes, only: [:create, :destroy]
    end
  end

  root :to => "pages#home"
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :comments

  validates :body, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :find_project
  before_filter :find_event, except: [:index, :new, :create]
  before_filter :authorize_user, only: [:new, :edit, :create, :update]

  def index
    @events = @project.events
  end

  def show
    @comment = Comment.new
  end

  def new
    @event = Event.new
  end

  def create
    params.require(:event).permit!
    @event = @project.events.build(params[:event])
    if @event.save
      flash[:notice] = "Successfully created Event"
      current_user.events << @event
    else
      flash[:alert] = "Could not add Event"
      redirect_to @project and return
    end
    redirect_to project_event_path(@project, @event)
  end

  def edit
  end

  def update
    params.require(:event).permit!
    if @event.update_attributes(params[:event])
      redirect_to project_event_path(@project, @event)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
  end

  private
    def find_project
      @project = Project.published.find_by_slug!(params[:project_id].split("/").last)
    end

    def find_event
      @event = @project.events.find(params[:id])
    end

    def authorize_user
      if @project.user != current_user
        flash[:alert] = "You do not have permission to create an event on this Pitch!"
        redirect_to @project and return
      end
    end
end

app/views/events/_comments.html.erb
<% if !@event.comments.blank? %>
  <% for comment in @event.comments %>
    <div>
      <%= comment.body %>
    </div>
    <div>
      <%= comment.user.email %>
    </div>
  <% end %>
<% else %>

<% end %>

app/views/events/_form.html.erb
<%= semantic_form_for [@project, @event] do |f| %>
  <%= f.inputs :name => "Event Details" do %>
    <%= f.semantic_errors *f.object.errors.keys %>
    <%= f.input :body %>
  <% end %>
    <%= f.actions :submit, :cancel %>
<% end %>

app/views/events/_new_comment.html.erb
<%= semantic_form_for [@project,@event,@comment] do |f| %>
  <%= f.inputs :name => "Add Comment" do %>
    <%= f.semantic_errors *f.object.errors.keys %>
    <%= f.input :body, :as => :text %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, :label => "Submit" %>
  <% end %>
<% end %>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <%= link_to project_event_path(@project,event) do %>
    <div>
      <%= event.body %>
    </div>
  <% end %>
<% end %>
<%= link_to "Back to Pitch", project_path(@project) %>

app/views/events/show.html.erb
<div>
  <%= @event.body %>
</div>
<% if @event.user == current_user %>
  <%= link_to "Edit Event", edit_project_event_path(@project,@event) %>
<% end %>
<%= render :partial => "comments" %>
<%= render :partial => "new_comment" if user_signed_in? %>
<%= link_to "Back to Pitch", project_path(@project) %>