config/routes.rb
Crowdvocate::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { :registrations => "user/registrations", :sessions => "user/sessions" }
  devise_scope :user do
    #get 'account(/:id)', :action => 'edit', :controller => 'user/registrations', :as => 'account'
  end
  ActiveAdmin.routes(self)
  match "/admin" => "admin/dashboard#index", via: :get

  get "pages/home"
  resources :projects do
    resources :events do
      resources :comments, only: [:create]
    end
    resources :pledges, only: [:create, :update]
    resources :videos do
      resources :votes, only: [:create, :destroy]
    end
  end

  root :to => "pages#home"
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :pledges
  has_many :events
  has_many :videos
  has_many :pledged_users, :through => :pledges, :source => :user

  after_initialize :init

  has_attached_file :image, :styles => { :main => "300x300>", :thumb => "100x100>" }, :default_url => "http://placehold.it/300x300&text=No+Photo"

  validates :slug, uniqueness: true, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :body, presence: true
  validates :goal, numericality: { only_integer: true, greater_than: 0 }
  validate :deadline_cannot_be_in_the_past

  def deadline_cannot_be_in_the_past
    if deadline.present? && deadline < Time.now
      errors.add(:deadline, "can't be in the past")
    end
  end

  before_validation :generate_slug

  scope :published, -> { where(published: true).where("published_at < ?", Time.zone.now).order('published_at DESC') }

  def to_param
    slug
  end

  def generate_slug
    self.slug ||= name.parameterize
  end

  def init
    self.published = false if (self.has_attribute? :published) && self.published.nil?
  end

  def raised
    self.pledges.to_a.sum(&:amount)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :find_project, except: [:index, :new, :create]

  def index
    @projects = Project.published
  end

  def show
    if @project.pledged_users.include?(current_user)
      @pledge = @project.pledges.where(:user => current_user).first
    else
      @pledge = Pledge.new
    end
  end

  def new
    @project = Project.new
  end

  def create
    params.require(:project).permit!
    @project = current_user.projects.build(params[:project])
    if @project.save
      flash[:notice] = "Successfully created Pitch"
    else
      flash[:alert] = "Could not save Pitch"
    end
    #To be changed to user.projects page
    redirect_to action: 'index'
  end

  def edit
  end

  def update
    params.require(:project).permit!
    if @project.update_attributes(params[:project])
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
  end

  private
    def find_project
      @project = Project.published.find_by_slug!(params[:id].split("/").last)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= semantic_form_for @project do |f| %>
  <%= f.inputs :name => "Pitch Details" do %>
    <%= f.semantic_errors *f.object.errors.keys %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :image %>
    <%= f.input :deadline, :as => :datetime_picker %>
    <%= f.input :goal %>
    <%= f.input :body %>
  <% end %>
    <%= f.actions :submit, :cancel %>
<% end %>

app/views/projects/_new_pledge.html.erb
<%= semantic_form_for [@project,@pledge] do |f| %>
  <%= f.inputs :name => "Pledge Funds" do %>
    <%= f.semantic_errors *f.object.errors.keys %>
    <%= f.input :amount %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit %>
  <% end %>
<% end %>

app/views/projects/index.html.erb
<%= link_to "Create a project", new_project_path %>
<% @projects.each do |project| %>
  <%= link_to project_path(project) do %>
    <div>
      <%= image_tag project.image.url(:main) %>
    </div>
    <div>
      <%= project.name %>
    </div>
    <div>
      <%= project.description %>
    </div>
  <% end %>
<% end %>

app/views/projects/new.html.erb
<%= semantic_form_for @project do |f| %>
  <%= f.inputs :name => "Pitch Details" do %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :image %>
    <%= f.input :deadline, :as => :datetime_picker %>
    <%= f.input :goal %>
    <%= f.input :body %>
    <%= f.input :published %>
    <%= f.input :published_at, :as => :datetime_picker %>
  <% end %>
    <%= f.actions %>
<% end %>

app/views/projects/show.html.erb
<div>
  <%= @project.name %>
</div>
<div>
  <%= @project.description %>
</div>
<div>
  <%= image_tag @project.image.url(:main) %>
</div>
<div>
  Goal = <%= @project.goal %>
</div>
<div>
  Raised = <%= @project.raised %>
</div>
<div>
  <%= @project.deadline %>
</div>
<div>
  <%= @project.body %>
</div>
<% if !@project.videos.blank? %>
  <% for video in @project.videos %>
    <div>
      <%= raw(video.url) %>
    </div>
    <div>
      Uploaded by <%= video.user.email %>
    </div>
    <div>
      <% if user_signed_in? %>
        <% if video.user == current_user %>
          <%= link_to "Edit Video", edit_project_video_path(@project,video) %>
          <%= link_to "Delete Video", project_video_path(@project,video), :method => 'delete' %>
        <% end %>
        <% if current_user.voted_videos.include?(video) %>
          <% vote = video.votes.where(:user => current_user).first %>
          <%= link_to "Remove Vote", project_video_vote_path(@project, video, vote), :method => :delete %>
        <% else %>
          <%= link_to "Upvote", project_video_votes_path(@project, video), :method => :post %>
        <% end %>
      <% end %>
    </div>
    <div>
      Votes : <%= video.votes.count %>
    </div>
  <% end %>
<% else %>

<% end %>
<% if user_signed_in? %>
  <%= render :partial => "new_pledge" %>
  <% if !current_user.video_projects.include?(@project) %>
    <%= link_to "Add Video", new_project_video_path(@project) %>
  <% end %>
<% end %>
<% if @project.user == current_user %>
  <%= link_to "Create Event", new_project_event_path(@project) %>
<% end %>
<%= link_to "All Events", project_events_path(@project) %>
<%= link_to "Back to Pitches", projects_path %>